# Generated by Django 3.0.5 on 2020-07-26 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'images',
            },
        ),
        migrations.RemoveField(
            model_name='listings',
            name='img_url',
        ),
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pic', to='auctions.Img'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='starter_bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.Bid'),
        ),
    ]
