# Generated by Django 3.0.5 on 2020-08-01 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200730_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.Listings'),
        ),
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pic', to='auctions.Listings'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='starter_bid',
            field=models.IntegerField(null=True),
        ),
    ]
