# Generated by Django 3.0.5 on 2020-08-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200802_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='comments',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
