# Generated by Django 3.0.5 on 2020-08-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200803_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='lastbid',
            field=models.IntegerField(null=True),
        ),
    ]
